input_filepath: data/processed
output_filepath: models/resnet50_semseg_ub.pt
epoch: 50
batch_size: 15
criterion: torch.nn.CrossEntropyLoss
optimizer: torch.optim.Adam
lr: 0.001
scheduler: torch.optim.lr_scheduler.StepLR
step_size: 25
gamma: 0.1


